### ISSUE TITLE
Sometimes we need to re-execute work when props change.

### ISSUE THREAD

**Issue by ctrlplusb** [ctrlplusb/react-jobs#13]
e.g.

```jsx
<Product id={productId />
```

If the parent component changes the id the new product may need to be fetched, but the component isn't remounted so this won't happen.

**Proposal**

Add a `monitorProps` configuration option.  Any time this value changes the work will fire again, even if the work is in progress as it will need to override any existing work.

```
withJob(
  ({ producId }) => fetchProduct(productId),
  { monitorProps: ['productId'] }
)(Product)
```

**Comment by ctrlplusb** [comment]
@smirea

**Comment by ctrlplusb** [comment]
Works rad in tests.

**Comment by ctrlplusb** [comment]
Done in 0.5.0

**Comment by smirea** [comment]
looks nice! 
this might be getting in the land of doing too much / being too opinionated though. There are use-cases for re-fetching based on sub-props for example, which this implementation does not currently support. 
How about implementing a generic `shouldFetch` or `shouldReFetch` method that takes in everything and returns a bool. the default could be 

```js
shouldFetch: ({job}) => !job || (!job.complete && !job.inProgress)
````

one could very easily monitorProps via:

```
shouldReFetch: (newProps, oldProps) => newProps.productID !== oldProps.productID
```

**Comment by ctrlplusb** [comment]
I like that a lot more!

**Comment by ctrlplusb** [comment]
Hey @smirea!

I have made some breaking changes here. 😀  It's pushed to master, but not yet published to npm.  I await your feedback prior. 😀

Changes:
  - Big refactor of `componentWillReceiveProps` lifecycle hooks.  We no longer provide a default strategy for this.  By default `work` functions will only get executed when a Component mounts. We now provide a new configuration property called `shouldWorkAgain`.  Define this configuration item if you would like to be able to control if and when `work` should be executed again when your Component receives new props.
  - The `monitorProps` configuration value has been removed, instead we have introduced an addon function (`react-jobs/addons/workAgainForMonitoredProps`) that can be used to set the new `shouldWorkAgain` configuration value. This provides the same functionality as was previously provided by the removed `monitorProps` configuration value.

See the [doc updates](https://github.com/ctrlplusb/react-jobs#withjobcreatework).

Let me know what you think?

**Comment by smirea** [comment]
looks good, great work! This has pretty much became the abstract helper I wrote for my own use-case so that's awesome :D

1 quick comment: https://github.com/ctrlplusb/react-jobs/commit/23fb2e66a71173ee68489c0f1aba4c8fdce22e1a#commitcomment-20503551

**Comment by smirea** [comment]
this is more conceptual, but I personally think that the `addons` go a bit beyond the scope of this package. Implementing `workAgainForMonitoredProps` solves a cool use-case, but it's not anything specific for this package - it is a generic props comparison method

The reason I mention this is that `shouldWorkAgain` is an optional option, checking props is an optional (yet very common) functionality and checking nested props (the bulk of what the addon does) is something that if you need, you probably have your own implementations (e.g. in by using memoized selectors with [reselect]()

**Comment by smirea** [comment]
(submitted this too early by mistake)

this is more conceptual, but I personally think that the addons go a bit beyond the scope of this package. Implementing workAgainForMonitoredProps solves a cool use-case, but it's not anything specific for this package - it is a generic props comparison method

If you need the addon functionality you can easily implement the most common use-case yourself without much hassle:

```js
// Only a bit more verbose
shouldWorkAgain: (props, nextProps) =>
    props.foo !== nextProps.foo || 
    props.bar !== nextProps.bar
```

A tad more hassle with nested props but doable as well. 
In practice, if you need the functionality of `workAgainForMonitoredProps`, you'd probably implement your own version tailored to your needs that's also re-usable outside of react-jobs 

e.g. most common use-case I can think of is with redux, where you need to get the things that you're checking against, and the pattern there generally is to hoist data from nested state to top level:

```js
@connect(state => ({
    image: selectImage(state),
    product: selectProduct(state),
})
@withJob(({dispatch, image}) => dispatch(fetchImage(image)), {
    shouldWorkAgain: (props, nextProps) => props.image !== nextProps.image
})
```

**Comment by ctrlplusb** [comment]
Fantastic feedback yet again @smirea!  I love having you as a collaborator.  This makes complete sense!  I am going to update the docs to reflect what you have recommended.  I won't remove the addon for now, I will just remove it from the docs.
