### ISSUE TITLE
evaluating react-jobs and react-resolver 

### ISSUE THREAD

**Issue by devdlabs** [ctrlplusb/react-jobs#16]
Hi @ctrlplusb I'm planning to use react-jobs or react-resolver for my next project. What do you suggest for browser side development ?  
I really need Observer type stuff but hesitate to use RxJS for now so what are simplest options?

**Comment by ctrlplusb** [comment]
Hey @devdlabs 

It's hard to say.  There is no blanket answer for anything. You will have to evaluate your needs a bit further and describe the problems you would like to solve.  If you want to have a loading/error status shown to the user then go for `react-jobs`.  If you want a longer standing and community backed library then go for `react-resolver`.  

Why do you think you need observables?

**Comment by devdlabs** [comment]
thanks @ctrlplusb We need to handle sockjs events and update the redux state, components etc for live updates etc. I love sockjs over socketio and need simple way to update appropriate action etc . Any thoughts? 
Thank you

**Comment by ctrlplusb** [comment]
Look at this, perhaps it may be a helpful reference?

https://github.com/michaelmitchell/redux-socket.io-connect

**Comment by devdlabs** [comment]
Thanks @ctrlplusb  it looks interesting
