### ISSUE TITLE
SSR: state set explicitly but rehydrated implicitly

### ISSUE THREAD

**Issue by djgrant** [ctrlplusb/react-jobs#17]
`runJobs` requires the developer to explicitly pass the state in a script tag.
`rehydrateJobs` gets the state itself. It has an implicit dependency on the global state created by the developer.

Could runJobs create the script tag itself?

For transparency sake it seems better if either both functions do magic to pass the state between server and client, or that the handover of state is explicit at both ends.

**Comment by ctrlplusb** [comment]
New API is much more explicit. 😀
