### ISSUE TITLE
withJob from "react-jobs" runs on SSR

### ISSUE THREAD

**Issue by smirea** [ctrlplusb/react-jobs#22]
the following code:

```jsx
import {withJob as withJobBrowser} from 'react-jobs';

@withJobBrowser(() => console.log('i should be in the browser') || Math.random())
class MyTest extends PureComponent {

    render () {
        const {job} = this.props

        return (
            <div>
                test: {job.result}
            </div>
        );
    }

}
```

prints `i should be in the browser` in node when server side rendering is enabled. 

My understanding was that `react-jobs` and `react-jobs/ssr` were mutually exclusive (i.e. the former should only run on the client and the latter only the server/client)

this is using the latest version - `0.6.2`

**Comment by ctrlplusb** [comment]
Hey @smirea with the latest release and API overhaul this is no longer applicable.

Closing 😀
