### ISSUE TITLE
Integrate with react-async-bootstrapper

### ISSUE THREAD

**Issue by mattoni** [ctrlplusb/react-jobs#24]
Hi there,

Excellent work, your series of libs for react SSR are the only things that seem to work with React Router v4.

I'm still looking for a solution for pre-rendering data on the server for SEO, in conjunction with your react-async-components lib. Is the plan for this library to work with react-async-bootstrapper as well so as to avoid multiple component tree walks? 

Thanks!

**Comment by ctrlplusb** [comment]
Hey @mattoni! Thanks!

Yep, exactly this. I had planned to get this running already but I haven't had the time as of yet. Hoping to land an alpha release soon.  I need to finish up the async-components upgrade first, already have a bunch of updates queued on my local.

I will keep you posted.

**Comment by mattoni** [comment]
Sounds good. Do you have any suggestions for an interim-hack in the meantime? I'm building a base repo for SSR for use throughout my company and am on a deadline.

https://github.com/mattoni/fusemob-ssr

Any help is appreciated, looking forward to the final release :) Oh, and I'm also curious if you've done any performance testing with this method. I love how I can use the native react-router v4 api, but a benefit of static routes would be not having to mount the tree. Just wondering how large a performance hit it would be in a larger app.

**Comment by ctrlplusb** [comment]
Hey @mattoni 

Sorry about the delayed response.  I am busy with a rewrite that integrates this.  Sorry, no absolute time frames right now, but I will keep you posted.

Regards;

**Comment by ctrlplusb** [comment]
I've updated the `next` branch README with the expected new API.

In regards to performance testing, I don't anticipate it adds much overhead.  I haven't done any testing but all you are doing is creating some objects via functions along the way.  Most of the overhead will be in the execution of your async functions but that should be expected.

I hope to one day create a repo to prove this though.

**Comment by ctrlplusb** [comment]
@mattoni an alpha has just been release. :)

Have yet to test it though, but will do soon.

**Comment by ctrlplusb** [comment]
Very close.  Needs a tiny bit more tweaking.  Will link you to the branch within `react-universally` when it is working.

**Comment by ctrlplusb** [comment]
Working! 🎉

Integrated into [`react-universally/@next/react-jobs`](https://github.com/ctrlplusb/react-universally/tree/%40next/react-jobs)

Demo: https://react-universally-jobs.now.sh
