### ISSUE TITLE
Legacy usage of propTypes not entirely cleaned up?

### ISSUE THREAD

**Issue by brianfeister** [ctrlplusb/react-jobs#31]
In the following image you can see the stack trace (this is from your `react-universally` project) originates with `JobProvider.js:100` where this commit (https://github.com/ctrlplusb/react-jobs/commit/c3177aa16c1b4d31f9a6b5d5c316bea997b11d71#diff-b7af30e277db47a2443c438bd5f49415R163) failed to swap the usage of the default `PropTypes` which is assumed to come from the `react` dependency but no longer does. 

I was going to work on perhaps PR'ing this, but being new to the React community I wanted to make sure I wasn't under some very high-level misunderstanding about this.

![image](https://cloud.githubusercontent.com/assets/806536/25683611/f8ccab64-302a-11e7-9645-b00e04d373d8.png)

**Comment by brianfeister** [comment]
When I make the following change in the compiled code (don't worry, I will commit it to src, not the complied result), the error in the console every time I load this dependency is cleaned up.
FROM:
```
JobProvider.childContextTypes = {
  jobs: _propTypes2.default.shape({
    getNextId: _propTypes2.default.func.isRequired,
    register: _propTypes2.default.func.isRequired,
    get: _propTypes2.default.func.isRequired,
    getRehydrate: _react2.default.PropTypes.func.isRequired,
    removeRehydrate: _react2.default.PropTypes.func.isRequired
  }).isRequired
```
TO:

```
JobProvider.childContextTypes = {
  jobs: _propTypes2.default.shape({
    getNextId: _propTypes2.default.func.isRequired,
    register: _propTypes2.default.func.isRequired,
    get: _propTypes2.default.func.isRequired,
    getRehydrate: _react2.default.PropTypes.func.isRequired,
    removeRehydrate: _react2.default.PropTypes.func.isRequired
  }).isRequired
```

**Comment by brianfeister** [comment]
And /cc @birkir since you can probably set me straight on why you changed the above methods, but not `getRehydrate` and `removeRehydrate`

**Comment by birkir** [comment]
Hey Brian.

This was fixed with #26 - I think the only thing left to do is to publish the package with the update.

The reason why this slipped through is probably because I rushed it so hard for react-universally upgrade to React 15.5, it was a big chain of packages.

**Comment by ctrlplusb** [comment]
Apologies, I'll get this published asap.

**Comment by ctrlplusb** [comment]
Sorted, apologies for delay. Busy boy of late.

**Comment by birkir** [comment]
Better late than never, as they say 😄
