### ISSUE TITLE
Reshow loading component if work runs again

### ISSUE THREAD

**Issue by deusd** [ctrlplusb/react-jobs#32]
I'd like to be be able to show the loading component if work is triggered again with 'shouldWorkAgain', is this possible?

It seems that the work is being triggered fine but the loading component doesn't show

**Comment by montezume** [comment]
Yeah, I'm having the same problem. Seems to me like just need to reset the jobStatus when it's ran again?

**Comment by ctrlplusb** [comment]
Yeah, this is likely a bug. 😞
