### ISSUE TITLE
Using rehydrateState to delay job

### ISSUE THREAD

**Issue by tijs** [ctrlplusb/react-jobs#35]
I'm trying to use redux-persist for some of my client rendered components using react-jobs but i'm not quite sure what the best way is to basically delay the `work()` until rehydration is done to prevent the result being overwritten by the persisted state. Any examples or hint on what would be the best way to hook this up?

**Comment by ctrlplusb** [comment]
Hmmm, is it not possible to fire the redux rehydration prior to calling render?
