### ISSUE TITLE
withJobs AND React Router Connection

### ISSUE THREAD

**Issue by jgrauel** [ctrlplusb/react-jobs#40]
If I am already leveraging the` withRouter(connect(mapStateToProps,actions))(App)` 
What is the proper structure to add in the withJobs? Or can it even be done?
I would like to have the "work" property (props) be the props which are the result of the withRouter? Any assistance would be welcome. My endgame would be to allow for the async resolution of data where i will be able to check the presence in the redux store before making the API call.
Thanks

**Comment by DPr00f** [comment]
@jgrauel I know this is a late reply, but I believe you can use compose to do that

```
export default compose(
  withRouter,
  connect(mapStateToProps, mapActionsToProps),
  withJob({
    work: ({ match, location }) => fetchPackage(location)
  })
)(App);
```
