### ISSUE TITLE
Add a "finished" job status

### ISSUE THREAD

**Issue by smirea** [ctrlplusb/react-jobs#5]
Just checking `error` + `inProgress` + `result` is not entirely sufficient to know if the job is finished if your promise does not resolve any value.

E.g:

```jsx
@withJob(() => Promise.resolve(undefined))
class Foo extends PureComponent {
    render () {
         const {job: {inProgress, error, result}} = this.props;
         if (error) return <div>Error</div>;
         if (inProgress) return <div>loading...</div>;
         return <div>{result}</div>;
    }
}
```

In the above example, the very first time a component is loaded, its state is 

`{inProgress: false, result: undefined, error: undefined}`

After the fetch completes and the promise resolves, it's status is going to be the same: 

`{inProgress: false, result: undefined, error: undefined}`

This is actually a common use-case when you pair this module with `redux` and `normalizr` as you generally don't return anything from the fetch() and your actions just populate the global cache:

```jsx
// This action does not necessarily guarantee an eventual resolve value
const getUser = () => fetch(...).then(result => dispatch(cacheUser(normalize(result)));

@connect(state => state.user, {getUser})
@withJob(({getUser}) => getUser())
class Foo extends PureComponent {}
```

**Suggestion:** Add a `finished` property that is set to true when the job has completed (either in success or failure). This can be checked against in the cases for which the promise resolves to `undefined`

**Comment by smirea** [comment]
to this note, @ctrlplusb I actually have a working path for this, but I'm unable to commit to the fork due to flow pre-commit errors not finding definitions for `describe`, `it` and `expect`

```
test/src/withJob.test.js:98
 98:       expect(actual).toMatchObject(expected);
           ^^^^^^ identifier `expect`. Could not resolve name
```

any suggestions on how to sort this out (I have the flow-typed installed)

**Comment by ctrlplusb** [comment]
Great suggestion @smirea!

**Comment by ctrlplusb** [comment]
@smirea sometimes the flow engine gets stuck, try run the following on the command line:

```
$(npm bin)/flow stop
$(npm bin)/flow start
```

FYI I am going to remove flow from the commit/publish hooks, so this shouldn't be a pain for much longer.

**Comment by ctrlplusb** [comment]
One small, silly request from my side, if you are doing a PR... :)

Would you mind renaming `finished` to `completed`?
