### ISSUE TITLE
Question: Does this plugin re-runs the server side code on succeeding requests?

### ISSUE THREAD

**Issue by iwoork** [ctrlplusb/react-jobs#52]
I'm currently using react-universally (that has react-jobs) and noticed that when I use:

```
withJob({
  work: {
    // call function that calls an API with CORS disabled
    fetch('http://www.example.com/api/demo')
    ....
    // On initial page load, this works as the server side connects to the API 
    // and returns the results from the API to the client side
  },
  shouldWorkAgain(prevProps, nextProps, jobStatus) {
    return prevProps.page !== nextProps.page // this returns true
  }
})
```
From the documentation, it says that the `work` triggers again once componentWillReceiveProps fires and also shouldWorkAgain is true. In my case, succeeding actions in my page (e.g pagination change) triggers the `work` again when props.page changes BUT throws a CORS error as it seems that the succeeding requests run only on the client side.

Does this plugin run a server-side requests consequently after the initial page load? My requirement is that whenever I call an API page, it should initially request to the 3rd party sites from the application's server side as to go around the CORS limitation.

**Comment by ctrlplusb** [comment]
Only the initial server call will result in the work being executed on the server. Once the app is mounted on the client then any subsequent work calls will be made via the browser. You will need to take this into account. One option would be to create a proxy API endpoint on your server to allow either the client/server to call and avoid CORS issues.
