### ISSUE TITLE
Why is there a need for a double-callback?

### ISSUE THREAD

**Issue by smirea** [ctrlplusb/react-jobs#8]
Throughout the readme the following pattern keeps popping up:

```jsx
@withJob(() => () => fetch(...))
class Foo {}
```
and the docs themselves clearly state

>   // Provide a function that will create a "work" function.

But checking the behavior and the code: https://github.com/ctrlplusb/react-jobs/blob/master/src/withJob.js#L64

I don't get how that is supposed to function. `work()` gets called and the props are passed to the top most method and, using the recommended syntax, the inner function gets returned as a result. 

It seems intuitive to me that the format should simply be

```jsx
@withJob(props => Promise.resolve())
class Foo {}
```

**Edit:** just using the above intuitive syntax actually works as expected

**Comment by ctrlplusb** [comment]
Ummm.... I think this may be a complete mess up on the docs!  I'll have a look thanks!

**Comment by ctrlplusb** [comment]
OMG, that was embarrassing.  I don't know why I wrote it out like that.  Parts of the README had it right and others not.  Thank you for that!
